POST http://localhost:3333/terreno
Content-Type: application/json

{
    "bairro": "Monte fuji",
    "lote": "lote 13",
    "quadra": 5
}

###

GET http://localhost:3333/terreno

###

GET http://localhost:3333/terreno?search= Monte fuji

###

PUT http://localhost:3333/terreno/
Content-Type: application/json

{
    "bairro": "Monte fuji",
    "lote": "lote 13",
    "quadra": 5
}

###

DELETE http://localhost:3333/terreno/